<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- 測試框架: 自研的樹型測試框架 -->
		<PackageReference Include="Tsinswreng.CsTreeTest" Version="0.1.1-alpha" />
		<!-- 被測的兩個庫 -->
		<ProjectReference Include="../Tsinswreng.CsErr/Tsinswreng.CsErr.csproj" />
		<ProjectReference Include="../Tsinswreng.CsErr.Results/Tsinswreng.CsErr.Results.csproj" />
	</ItemGroup>

</Project>
